#
# COPYRIGHT Ericsson 2023
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

eric-data-document-database-pg:
  postgresDatabase: csacdb
  nameOverride: eric-oss-core-slice-assurance-cfg-db
  credentials:
    kubernetesSecretName: eric-oss-core-slice-assurance-cfg-db-secret
    keyForUserId: pguserid
    keyForUserPw: pgpasswd
    keyForSuperPw: super-pwd

wiremock:
  fullnameOverride: wiremock

global:
  pullSecret: k8s-registry
  security:
    tls:
      enabled: false
