#
# COPYRIGHT Ericsson 2024
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.edb.secretName }}
  labels:
    chart: {{ template "dev-env.chart" . }}
  {{- include "dev-env.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "dev-env.helm-annotations" .| nindent 4 }}
type: Opaque
data:
  super-user: {{ .Values.edb.settings.superuser | b64enc }}
  super-pwd: {{ .Values.edb.settings.superuserPassword | b64enc }}
