#
# COPYRIGHT Ericsson 2024
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
metadata:
  name: ms-edb-client-cert-auto
  labels:
    chart: {{ template "dev-env.chart" . }}
  {{- include "dev-env.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "dev-env.helm-annotations" .| nindent 4 }}
type: Opaque
data:
  client.key: {{ .Files.Get "secrets/client/client.key" | b64enc | indent 2 }}
  client.crt: {{ .Files.Get "secrets/client/client.crt" | b64enc | indent 2 }}
  client-key.pk8: {{ .Files.Get "secrets/client/client-key.pk8" | b64enc | indent 2 }}
