#
# COPYRIGHT Ericsson 2024
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.dummyCreds }}
  labels:
    chart: {{ template "dev-env.chart" . }}
  {{- include "dev-env.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "dev-env.helm-annotations" .| nindent 4 }}
type: Opaque
data:
  pguserid: {{ print "dummyuser" | b64enc }}
  pgpasswd: {{ print "custompwd" | b64enc }}
  super-pwd: {{ print "superpwd" | b64enc }}
  super-user: {{ print "postgres" | b64enc }}
  replica-pwd: {{ print "replicapwd" | b64enc }}
  replica-user: {{ print "replicauser" | b64enc }}
  kcadminid: {{ print "adminid" | b64enc }}
  kcpasswd: {{ print "adminpwd" | b64enc }}
  metrics-pwd: {{ print "metricspwd" | b64enc }}
