# Default values for wiremock.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: armdockerhub.rnd.ericsson.se/wiremock/wiremock
  tag:  sha256__3b9285a939269e8e9a95a786aecb31560f4845a42312010da67b35db2117cbdf
  pullPolicy: IfNotPresent

service:
  name: wiremock
  type: ClusterIP
  httpPort: 8080
  httpsPort: 8443

fullnameOverride: wiremock

global:
  security:
    tls:
      enabled: false
