apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiremock.fullname" . }}-responses-configs
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "wiremock.name" . }}
    helm.sh/chart: {{ include "wiremock.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- (.Files.Glob "mocker/data/__files/**.json").AsConfig | nindent 2 }}
