apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiremock.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "wiremock.name" . }}
    helm.sh/chart: {{ include "wiremock.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: {{ .Values.service.name }}-http
  {{- if .Values.global.security.tls.enabled }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.httpsPort }}
      protocol: TCP
      name: {{ .Values.service.name }}-https
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "wiremock.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
