#
# COPYRIGHT Ericsson 2022
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

version: '3'
services:
  wiremocker:
    image: wiremock/wiremock
    ports:
      - 8080:8080
    volumes:
      - ./helmCharts/wiremock/mocker/data:/home/wiremock
    command:
      - "--verbose"
  db:
    image: postgres:11.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/init_csac.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local
