#
# COPYRIGHT Ericsson 2024
# 
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

{{- $g := fromJson (include "eric-oss-core-slice-assurance-cfg.global" .) -}}
{{- if $g.security.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-oss-core-slice-assurance-cfg.name" . }}-tls-keystore-creds-secret
  labels:
  {{- include "eric-oss-core-slice-assurance-cfg.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-core-slice-assurance-cfg.prometheus" . | nindent 4 }}
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  passwd: {{ (randAlphaNum 32 | b64enc) | quote }}
  keyPasswd: {{ (randAlphaNum 32 | b64enc) | quote }} 
{{- end }}
