#
# COPYRIGHT Ericsson 2023
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

documents:
  # document name
  - name: user_guide
    # file names of files to be packaged in the document
    files:
      - ../doc/service-user-guide/service_user_guide.md
      - ../doc/service-user-guide/images/csac_service_architecture.png
      - ../doc/service-user-guide/images/csac-deployment-view.png
  - name: developers_guide
    files:
      - ../doc/app-dev-guide/application-developers-guide.md
      - ../doc/app-dev-guide/pmsc-kpi-model.png
  - name: database_design_guide
    files:
      - ../doc/database-design-guide/csac-database-schema.md
      - ../doc/database-design-guide/images/csac_db_erd.png

