#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

# Based on https://eteamspace.internal.ericsson.com/display/ACD/KubeAudit+Scanning
Kubeaudit:
  Product: 'eric-oss-core-slice-assurance-cfg Application'
  Product_internal: 'eric-oss-core-slice-assurance-cfg'
  Product_contact: 'PDLPDLSWOR@pdl.internal.ericsson.com'
  ClusterMode:
    AuditPickerFile: '' #Optional, #https://github.com/Shopify/kubeaudit#configuration-file, #Mount the dir containing this file to conf
    Autofix: false #(or True it if needed)
    AutofixedFile: '' #Mandatory If Autofix enabled, file name inside Mounted reports dir to add corrected config
    DisplayReportConsole: false #Make it true if you want the reports to be displayed in console
    ReportFormat: json #logrus,pretty are other available options. pretty is the default if not given.
    Scan: false
  ManifestMode:
    AuditPickerFile: '' #Optional #https://github.com/Shopify/kubeaudit#configuration-file, #Mount the dir containing this file to conf
    Autofix: false #(or True it if needed)
    AutofixDir: '' #Mandatory If Autofix enabled, folder name inside mounted reports dir to add corrected Yamls
    DisplayReportConsole: false #Make it true if you want the reports to be displayed in console
    ReportFormat: json #logrus,pretty are other available options. Pretty is the default if not given.
    Scan: true
    armLinks:
      Links: #
      valuesOverride: # Array. If override is needed, add the values yaml names in the same order as arm links, if none, mark it ''
    offlineArtifacts:
      name:
        - ''
      valuesOverride:   # If override is needed, add the values yaml names in the same order as offlineArtifacts name, if none, mark it ''
        - ''  # Mount this to /opt/va-scan-kubeaudit/conf dir
  CustomRun:
    Scan: False # This if True, overrides all the above options.
    # Give any valid kubeaudit command here
    # Place and mount the needed config files in /opt/va-scan-kubeaudit/conf/"
    Parameters: '' # Ex: "all -c /opt/va-scan-kubeaudit/conf/admin.conf"
    DisplayReportConsole: False # Make it true if you want the reports
