#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

model_version: 2.0
product_va_config:
  name: eric-oss-core-slice-assurance-cfg
  product_name: eric-oss-core-slice-assurance-cfg
  product_number: APR 201 702
  version: {version}
  va_template_version: 2.0.0
  description: >-
    eric-oss-core-slice-assurance-cfg Microservice
  spoc: "**TODO**"
  images:
    - eric-oss-core-slice-assurance-cfg:{version}
  # List of issue trackers used for citing Trouble Reports at the migitations
  # (see below).
  issue_trackers:
    # The `default` key is looked up if no hint provided on what tracker
    # should be used.  This is not added automatically, one has to provide
    # this explicitly.
    default: "https://eteamproject.internal.ericsson.com/browse/"
  mitigations:
    open_ports:
      "8443/tcp":
        # Change this to `true` if intended.
        intended: true
        # For intended ports, the `description` and `mitigation` keys and their values could be removed,
        # otherwise:
        # - describe why the port is open
        description: >-
          Intended, this is the port for the microservice REST API interface
