#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

# Default values for eric-oss-core-slice-assurance-cfg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# global:
#   createSchema: true
#  timezone: UTC
#  registry:
#    repoPath:
#    url: armdocker.rnd.ericsson.se
#    pullPolicy: IfNotPresent
#  #Secret must be manually created in the namespace, no default value
#  pullSecret: eric-adp-example-secret
#  fsGroup:
#    manual: 10000
#    namespace: true
#  # The IP family the service belongs to when service.type is set to ClusterIP.
#  # Options are: IPv4, IPv6
#  internalIPFamily:
#  security:
#    policyBinding:
#      create: true
#    policyReferenceMap:
#      default-restricted-security-policy: "<restricted security policy at customer deployment>"
#    tls:
#      enabled: true
#      trustedInternalRootCa:
#        secret: "eric-sec-sip-tls-trusted-root-cert"

replicaCount: 1

podDisruptionBudget:
  # Minimum number/percentage of Pods that must remain available during the planned disruption.
  # Value can be expressed as an integer or as a percentage. When specified as a percentage of the Pods,
  # if it does not map to an exact number, Kubernetes rounds up to the nearest integer.
  # minAvailable: 2 # example value for 2 pods defined as integer
  minAvailable: "40%"

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

#Empty labels list for application deployment engineer to add more labels (In Compliance with DR-D1121-068).
labels: { }

imageCredentials:
  repoPath: # overrides repoPath from eric-product-info.yaml
  eric-oss-core-slice-assurance-cfg:
    repoPath: # see default in eric-product-info.yaml
    registry: { }
    # overrides global registry url
    # url:
    #- Secret must be manually created in the namespace, no default value
    # pullSecret: REPO_SECRET
  eric-oss-core-slice-assurance-cfgTest:
    repoPath: # see default in eric-product-info.yaml

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: { }

annotations: { }

service:
  type: ClusterIP
  # The port defaults to 8080 if TLS is disabled and to 8443 if TLS is enabled
  # Only set this value to override the defaults
  port:
  endpoints:
    chassisapi:
      tls:
        enforced: required
        verifyClientCertificate: required
database:
  host: eric-oss-core-slice-assurance-cfg-db
  port: 5432
  # jdbcUrl is an optional parameter, when it is empty, it will build using the vendor, host, port, and dbName.
  jdbcUrl:
  vendor: postgresql
  secret: eric-oss-core-slice-assurance-cfg-db-secret
  userKey: pguserid
  passwdKey: pgpasswd
  dbaUserKey: super-user
  dbaPasswdKey: super-pwd
  dbName: csacdb

  # database SSL related config
  sslMode: disable
  serverCertSecret: edb-server-cert
  clientCertSecret: csac-edb-client-cert
  clientCertKey:  client.key
  clientCertRoot: client.crt
  serverCertKey: cacert.crt

  connectionTimeout: 60000
  connectRetries: 9
  dictSchema: dict
  rtSchema: rtds

# TLS keystore password and key password are provided by a secret.
# If not specified, the secret will be created on deployment. If
# specified, it must be created prior to deploying this service.
keystore:
  creds:
    secret:
    passwdKey: passwd
    keyPasswdKey: keyPasswd

csac:
  resource:
    # list of out-of-box resource files. Files will be loaded in the order
    # they are listed below.  OOB files are always loaded and validated
    # before custom resources are loaded.
    oob:
      - 'csac-oob-kpi-defs.json'
      - 'csac-oob-site-nssi-aggregation.json'
      - 'csac-ran-oob-kpi-defs.json'
      - 'Partial-DRB-Accessibility.json'
      - 'csac-core-oob-kpi-2.1.0.json'
      - 'csac-oob-esoa-13026.json'
      - 'csac-oob-esoa-13341.json'
      - 'csac-oob-esoa-13829.json'

eric-pm-server:
  rbac:
    appMonitoring:
      enabled: true

validation:
  external:
    enabled: true
    schemaRegistry:
      url: http://eric-schema-registry-sr:8081
      retry:
        maxRetryAttempts: 10
        waitDuration: 60000
        maxDelay: 600000
    dataCatalog:
      url: "http://eric-oss-data-catalog:9590"
      retry:
        maxRetryAttempts: 10
        waitDuration: 60000
        maxDelay: 600000

provisioning:
  aas:
    enabled: false
    url: "http://eric-oss-assurance-augmentation:8080"
    retry:
      maxRetryAttempts: 10
      waitDuration: 60000
      maxDelay: 600000
    # list of ARDQ Id/URL pairs for known ARDQ services.  The default is CARDQ
    ardq:
      cardq: http://eric-oss-core-reporting-dimension-query:8080
    ardqRetry:
      maxRetryAttempts: 10
      waitDuration: 60000
      maxDelay: 600000

  pmsc:
    legacy: false
    enabled: false
    url: "http://eric-oss-pm-stats-calculator:8080"
    retry:
      maxRetryAttempts: 10
      waitDuration: 60000
      maxDelay: 600000
    model:
      legacy: false
    data:
      reliabilityOffset: 0
    aggregationPeriod:
      # Default aggregation period in minutes for KPI calculations.
      # Must be one of 15, 60, or 1440
      default: 15
  index:
    enabled: false
    force: false
    url: "http://eric-oss-assurance-indexer:8080"
    legacy: false
    retry:
      maxRetryAttempts: 10
      waitDuration: 60000
      maxDelay: 600000
    source:
      pmstatsexporter:
        name: "pm-stats-calc-handling-avro-scheduled"

prometheus:
  path: /actuator/prometheus
  scrape: true

terminationGracePeriodSeconds: 30

resources:
  eric-oss-core-slice-assurance-cfg:
    requests:
      memory: 2Gi
      cpu: 500m
      ephemeral-storage: ""
    limits:
      memory: 2Gi
      cpu: 500m
      ephemeral-storage: ""
    jvm:
      initialMemoryAllocationPercentage: 50
      smallMemoryAllocationMaxPercentage: 70
      largeMemoryAllocationMaxPercentage: 50
  eric-oss-core-slice-assurance-cfgTest:
    requests:
      memory: 128Mi
      cpu: 50m
      ephemeral-storage: ""
    limits:
      memory: 1Gi
      cpu: 256m
      ephemeral-storage: ""
    jvm:
      initialMemoryAllocationPercentage: 50
      smallMemoryAllocationMaxPercentage: 70
      largeMemoryAllocationMaxPercentage: 50

autoScaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: { }
topologySpreadConstraints:
  deployment: [ ]
  test: [ ]

tolerations:
  - key: node.kubernetes.io/not-ready
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 0
  - key: node.kubernetes.io/unreachable
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 0

affinity:
  podAntiAffinity: "soft"
  topologyKey: "kubernetes.io/hostname"

probes:
  eric-oss-core-slice-assurance-cfg:
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 120
      periodSeconds: 10
      timeoutSeconds: 10
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 120
      periodSeconds: 10
      timeoutSeconds: 10

podPriority:
  eric-oss-core-slice-assurance-cfg:
    priorityClassName: ""
# choice='unconfined, runtime/default, localhost' [ default= runtime/default ]
# Configuration of AppArmor profile type. The following values are possible:
# unconfined  - Indicates that there is no profile loaded.
# runtime/default - Applies the default profile of the container engine.
# localhost   - Applies a specific profile loaded on the host
appArmorProfile:
  type: runtime/default
seccompProfile:
  type: RuntimeDefault

kubernetesDefaultService:
  url: https://kubernetes.default.svc.cluster.local

# Set to Default local streamingMethod
# Can be one of the following:
#   direct: Direct streaming to the Log Aggregator (Log Transformer).
#   indirect: Stdout to infrastructure logging framework.
#   dual: Stdout to infrastructure logging framework and direct streaming to Log Aggregator.
#   null - null or absent parameter the streaming method is determined by global.log.streamingMethod
log:
  streamingMethod: null
